config/routes.rb
MondrianDemo::Application.routes.draw do
  resources :physical_location_records

  resources :mdx do
    collection do
      get 'builder'
    end
  end

end

app/models/physical_location_record.rb
class PhysicalLocationRecord < ActiveRecord::Base
  belongs_to :physical_location,
             :inverse_of => :physical_location_record,
             :class_name => "OutOfHomeLocation"

  delegate :type, :resource_name, :address, :end_date,
           :start_date, :ends_episode?,
           :to => :physical_location, :allow_nil => true
  #Using the delegation design pattern here. The methods to get
  #start_date etc are actually provided by the PhysicalLocation
  #class.

end

app/controllers/physical_location_records_controller.rb
class PhysicalLocationRecordsController < ApplicationController
  # GET /physical_location_records
  # GET /physical_location_records.xml
  def index
    @physical_location_records = PhysicalLocationRecord.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @physical_location_records }
    end
  end

  # GET /physical_location_records/1
  # GET /physical_location_records/1.xml
  def show
    @physical_location_record = PhysicalLocationRecord.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @physical_location_record }
    end
  end

  # GET /physical_location_records/new
  # GET /physical_location_records/new.xml
  def new
    @physical_location_record = PhysicalLocationRecord.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @physical_location_record }
    end
  end

  # GET /physical_location_records/1/edit
  def edit
    @physical_location_record = PhysicalLocationRecord.find(params[:id])
  end

  # POST /physical_location_records
  # POST /physical_location_records.xml
  def create
    @physical_location_record = PhysicalLocationRecord.new(params[:physical_location_record])

    respond_to do |format|
      if @physical_location_record.save
        format.html { redirect_to(@physical_location_record, :notice => 'Physical location record was successfully created.') }
        format.xml  { render :xml => @physical_location_record, :status => :created, :location => @physical_location_record }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @physical_location_record.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /physical_location_records/1
  # PUT /physical_location_records/1.xml
  def update
    @physical_location_record = PhysicalLocationRecord.find(params[:id])

    respond_to do |format|
      if @physical_location_record.update_attributes(params[:physical_location_record])
        format.html { redirect_to(@physical_location_record, :notice => 'Physical location record was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @physical_location_record.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /physical_location_records/1
  # DELETE /physical_location_records/1.xml
  def destroy
    @physical_location_record = PhysicalLocationRecord.find(params[:id])
    @physical_location_record.destroy

    respond_to do |format|
      format.html { redirect_to(physical_location_records_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/physical_location_records_helper.rb
module PhysicalLocationRecordsHelper
end

app/views/physical_location_records/_form.html.erb
<%= form_for(@physical_location_record) do |f| %>
  <% if @physical_location_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@physical_location_record.errors.count, "error") %> prohibited this physical_location_record from being saved:</h2>

      <ul>
      <% @physical_location_record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/physical_location_records/edit.html.erb
<h1>Editing physical_location_record</h1>

<%= render 'form' %>

<%= link_to 'Show', @physical_location_record %> |
<%= link_to 'Back', physical_location_records_path %>

app/views/physical_location_records/index.html.erb
<h1>Listing physical_location_records</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @physical_location_records.each do |physical_location_record| %>
  <tr>
    <td><%= link_to 'Show', physical_location_record %></td>
    <td><%= link_to 'Edit', edit_physical_location_record_path(physical_location_record) %></td>
    <td><%= link_to 'Destroy', physical_location_record, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Physical location record', new_physical_location_record_path %>

app/views/physical_location_records/new.html.erb
<h1>New physical_location_record</h1>

<%= render 'form' %>

<%= link_to 'Back', physical_location_records_path %>

app/views/physical_location_records/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_physical_location_record_path(@physical_location_record) %> |
<%= link_to 'Back', physical_location_records_path %>